version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0

executors:
  default:
    docker:
      - image: cimg/ruby:3.2
    resource_class: small

jobs:
  rspec-test:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test

  build:
    executor: default
    steps:
      - checkout
      - run: gem build stopwords-filter2

  deploy:
    executor: default
    steps:
      - checkout
      - run:
          name: Setup rubygems auth
          command: |
            mkdir -p ~/.gem
            echo ":rubygems_api_key: $RUBYGEMS_API_KEY" > ~/.gem/credentials
            chmod 0600 ~/.gem/credentials
      - run: gem build stopwords-filter2
      - run:
          name: Publish version << pipeline.git.tag >>
          command: gem push stopwords-filter2-<< pipeline.git.tag >>
      - run: shred -u ~/.gem/credentials

workflows:
  build:
    jobs:
      - rspec-test:
          matrix:
            parameters:
              ruby-version: ["2.4", "2.5", "2.6", "2.7", "3.0", "3.1", "3.2"]

      - build

      - deploy:
          context:
            - rubygems-publishing
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - /.*/