version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0

jobs:
  build:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: cimg/ruby:<< parameters.ruby-version >>
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test

workflows:
  build:
    jobs:
      - build:
          matrix:
            parameters:
              ruby-version: ["1.9", "2.5", "2.6", "2.7", "3.0", "3.1", "3.2"]